name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 * * 0'

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    name: Test on Node.js ${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test dependencies

  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    name: Build on Node.js ${{ matrix.node }}
    steps:
      - name: Build
        run: pnpm build

  CodeQL:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go, javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
